# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.wordList:
        class: AppBundle\Game\WordList
        calls:
            - [addLoader, ['txt', '@app.textFileLoader']]
            - [addLoader, ['xml', '@app.xmlFileLoader']]
            - [addWord, ['customer']]
            - [addWord, ['lemonade']]
            - [addWord, ['employee']]
            - [loadDictionaries, ['%dictionaries%']]
    app.textFileLoader:
        class: AppBundle\Game\Loader\TextFileLoader
    app.xmlFileLoader:
        class: AppBundle\Game\Loader\XmlFileLoader
    app.gameContext:
        class: AppBundle\Game\GameContext
        arguments: ["@session"]
    app.gameRunner:
        class: AppBundle\Game\GameRunner
        arguments: ["@app.gameContext", "@app.wordList"]
    app.listener.openClose:
        class: AppBundle\EventListener\OpenCloseListener
        arguments: ["@twig"]
        tags:
            - {name: kernel.event_subscriber}