# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.wordList:
        class: AppBundle\Game\WordList
        calls:
            - [loadDictionaries, ['%dictionaries%']]
    app.textFileLoader:
        class: AppBundle\Game\Loader\TextFileLoader
        tags:
            - {name: hangman.loader, type: txt}
    app.xmlFileLoader:
        class: AppBundle\Game\Loader\XmlFileLoader
        tags:
            - {name: hangman.loader, type: xml}
    app.gameContext:
        class: AppBundle\Game\GameContext
        arguments: ["@session"]
    app.gameRunner:
        class: AppBundle\Game\GameRunner
        arguments: ["@app.gameContext", "@app.wordList"]
    app.listener.openClose:
        class: AppBundle\EventListener\OpenCloseListener
        arguments: ["@twig"]
        tags:
            - {name: kernel.event_subscriber}
    app.security.voter:
        class: AppBundle\Security\PlayerVoter
        public: false
        arguments: ['@security.access.decision_manager']
        tags:
            - { name: security.voter }